# Generated by Django 4.2.16 on 2024-10-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing"),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="watchlister",),
    ]
