# Generated by Django 4.2.16 on 2024-10-16 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_remove_listing_watchlister"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="poster",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="your_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
