# Generated by Django 4.2.16 on 2024-10-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_remove_listing_poster_bid"),
    ]

    operations = [
        migrations.DeleteModel(name="Bid",),
    ]
