# Generated by Django 4.2.16 on 2024-10-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_bid_price_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "listing",
                    models.ManyToManyField(
                        blank=True,
                        related_name="your_categories",
                        to="auctions.listing",
                    ),
                ),
            ],
        ),
    ]
