# Generated by Django 4.2.16 on 2024-10-16 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_comment_comment_alter_comment_commenter"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="winner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="your_wins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
