# Generated by Django 4.2.16 on 2024-10-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_listing_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
