# Generated by Django 4.2.16 on 2024-10-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_listing_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="winner",),
    ]
