# Generated by Django 4.2.16 on 2024-10-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0018_listing_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="bid_list",
            field=models.ManyToManyField(
                blank=True, related_name="your_bids", to="auctions.bid"
            ),
        ),
    ]
