# Generated by Django 4.2.16 on 2024-10-17 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0019_listing_bid_list"),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="bid_list",),
        migrations.AddField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids_list",
                to="auctions.listing",
            ),
            preserve_default=False,
        ),
    ]
