# Generated by Django 4.2.16 on 2024-10-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0021_remove_listing_watchlister_comment_listing_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid", name="price", field=models.FloatField(),
        ),
    ]
